#!/bin/bash
# If not running interactively, don't do anything
if [ -z "$PS1" ]; then
   return
fi

export castledir=~/castle
export dotfiles=$castledir/dotfiles
export cfgdir=$dotfiles/shell
osSuffix=$(uname|tr '[:upper:]' '[:lower:]')

if [[ "darwin" == "$osSuffix" ]]; then
	hostSuffix=$(scutil --get ComputerName)
else
	hostSuffix=$(hostname | cut -d. -f1)
fi

export osSuffix hostSuffix

include() {
	local master=$cfgdir/$1
	local os=$cfgdir/$1-$osSuffix
	local host=$cfgdir/$1-hostSuffix

	for bashfile in $master $os $host; do
		if [ -r "$bashfile" ]; then
			echo "Including $(basename "$bashfile")"
			. $bashfile
		fi
	done
}

shellStart=$(date +%s)
include bashrc
shellEnd=$(date +%s)
export shellStart shellEnd

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
