#!/bin/bash
if [ -z "$PS1" ]; then
   return
fi

myshelldir=~/myshell
dotfiles=$myshelldir/dotfiles
cfgdir=$dotfiles/shell

osSuffix=$(uname|tr 'A-Z' 'a-z')
hostSuffix=$(hostname | cut -d. -f1)
for fname in "bashrc"; do
	master=$cfgdir/$fname
	os=$cfgdir/$fname-$osSuffix
	host=$cfgdir/$fname-$hostSuffix

	echo -n "Reading shell config: "
	for bashfile in $master $os $host; do
		if [ -r $bashfile ]; then
			. $bashfile
			echo -n "`basename $bashfile` "
		fi
	done
done

echo
