#!/bin/bash
# Generated by cask-dotfile-generator
# Created by: @seethroughtrees
# https://github.com/seethroughtrees/brew-cask-dotfile-generator
#
brew update

brew upgrade

brew tap caskroom/versions
brew tap homebrew/dupes
brew tap homebrew/headonly
brew tap pivotal/tap
brew tap thoughtbot/formulae

brew install ack || true
brew install ant || true
brew install apple-gcc42 || true
brew install asciidoc || true
brew install aspell || true
brew install autoconf || true
brew install automake || true
brew install bash-completion || true
brew install bgrep || true
brew install bindfs || true
brew install bison || true
brew install boost || true
brew install boot2docker || true
brew install brew-cask || true
brew install caskroom/cask/brew-cask
brew install bvi || true
# brew install cairo || true
brew install cloc || true
brew install cloudfoundry-cli || true
brew install cmake || true
brew install couchdb || true
brew install cscope || true
brew install ctags || true
brew install docbook || true
brew install docbook-xsl || true
brew install docker || true
brew install dos2unix || true
brew install dwdiff || true
brew install e2fsprogs || true
brew install editorconfig || true
brew install encfs || true
brew install erlang || true
brew install exiftool || true
brew install fmdiff || true
brew install fontconfig || true
brew install freetype || true
brew install fuse4x-kext || true
brew install gdbm || true
brew install gettext || true
brew install git || true
brew install git-flow || true
brew install glib || true
brew install gmp || true
brew install gnu-getopt || true
brew install gnu-tar || true
brew install gnutls || true
brew install go || true
brew install gobject-introspection || true
brew install gradle || true
brew install graphviz || true
brew install icu4c || true
brew install imagemagick || true
brew install ios-webkit-debug-proxy || true
brew install jenkins || true
brew install jpeg || true
brew install jpeg-turbo || true
brew install jpegoptim || true
brew install --HEAD jpegrescan || true
brew install jq || true
brew install jsawk || true
brew install jsonpp || true
brew install leveldb || true
# brew install liberty-completion || true
brew install libevent || true
brew install libffi || true
brew install libgcrypt || true
brew install libgpg-error || true
brew install libimobiledevice || true
brew install libksba || true
brew install libplist || true
brew install libpng || true
brew install libtasn1 || true
brew install libtiff || true
brew install libtool || true
brew install libusb || true
brew install libxml2 || true
brew install libyaml || true
brew install liftoff || true
brew install little-cms2 || true
brew install lua || true
brew install lynx || true
brew install makedepend || true
brew install markdown || true
brew install md5sha1sum || true
brew install mercurial || true
brew install mongodb || true
brew install mtr || true
brew install mysql || true
brew install n || true
brew install nasm || true
brew install neon || true
brew install nettle || true
brew install nginx || true
brew install nspr || true
brew install nss || true
brew install ntfs-3g || true
brew install openjpeg || true
brew install openssl || true
brew install optipng || true
brew install osxfuse || true
brew install p11-kit || true
brew install p7zip || true
brew install parallel || true
brew install pcre || true
# brew install pdfgrep || true
brew install phantomjs || true
brew install pigz || true
brew install pixman || true
brew install pkg-config || true
# brew install poppler || true
brew install pv || true
brew install python || true
brew install qpdf || true
brew install rbenv || true
brew install readline || true
brew install reattach-to-user-namespace || true
brew install redis || true
brew install rlog || true
brew install rpm2cpio || true
brew install ruby-build || true
brew install scala || true
brew install scons || true
brew install shellcheck || true
brew install slimerjs || true
brew install sloccount || true
brew install snappy || true
brew install sonar || true
brew install spidermonkey || true
brew install sqlite || true
brew install ssh-copy-id || true
brew install sshfs || true
brew install subversion || true
brew install task || true
brew install the_silver_searcher || true
brew install thrift || true
brew install tig || true
brew install timedog || true
brew install tmux || true
brew install tree || true
brew install ttyrec || true
brew install uncrustify || true
brew install unixodbc || true
brew install unrar || true
brew install usbmuxd || true
brew install v8 || true
brew install vim --with-lua --with-perl || true
brew install webkit2png || true
brew install wget --enable-iri || true
brew install wxmac || true
brew install xctool || true
brew install xmlformat || true
brew install xmlstarlet || true
brew install xmlto || true
brew install xulrunner || true
brew install xz || true
brew install yasm || true
brew install youtube-dl || true
brew install z || true

brew cleanup

