#!/bin/bash
# make backups
if [ -r ~/.bashrc ]; then
	mv ~/.bashrc ~/bashrc.dotfile
fi

if [ -r ~/.bash_profile ]; then
	mv ~/.bash_profile ~/bash_profile.dotfile
fi

if [ -r ~/.bash_logout ]; then
	mv ~/.bash_logout ~/bash_logout.dotfile
fi

shelldir=~/myshell
dotfiles=$shelldir/dotfiles
cfgdir=$dotfiles/shell

osSuffix=$(uname|tr 'A-Z' 'a-z')
hostSuffix=$(hostname | cut -d. -f1)

# link to bootstrap file
ln -s $shelldir/bootstrap ~/.bashrc

# link to most specific version available
for fname in "bash_profile" "bash_logout"; do
	master=$cfgdir/$fname
	os=$cfgdir/$fname-$osSuffix
	host=$cfgdir/$fname-$hostSuffix
	for bashfile in $host $os $master; do
		if [ -r $bashfile ]; then
			ln -s $bashfile ~/.$fname
			break
		fi
	done
done
