#! /bin/bash
# Some example alias instructions
# If these are enabled they will be used instead of any instructions
# they may mask.  For example, alias rm='rm -i' will mask the rm
# application.  To override the alias instruction use a \ before, ie
# \rm will call the real rm not the alias.

# Interactive operation...
# alias rm='rm -i'
# alias cp='cp -i'
# alias mv='mv -i'

# Misc :)
# alias less='less -r'                          # raw control characters
# alias whence='type -a'                        # where, of a sort

# Default to human readable figures
alias df='df -h'
alias du='du -h'

# Some shortcuts for different directory listings
# alias ls='ls -hF --color=tty'                 # classify files in colour
# alias dir='ls --color=auto --format=vertical'
# alias vdir='ls --color=auto --format=long'
alias ll='ls -l'
alias la='ls -A'
alias l='ls -lAF'
#alias lc='ls -CF'
alias lc="(printf 'PERM LINKS OWNER GROUP SIZE MONTH DAY HH:MM/YEAR NAME\n'; ls -la | sed 1d) | column -t"
alias cd..="cd .."
alias ..="cd .."
alias ...="cd ..."
alias md="mkdir"
alias grep='grep --color'
#alias mp="makeProject"
#alias sp=". setProject"
alias t='task'

# If using Linux alias pbcopy and pbpaste
if [[ "$OSTYPE" =~ ^linux ]]; then
	alias pbcopy='xsel --clipboard --input'
	alias pbpaste='xsel --clipboard --output'
fi

alias e="\$EDITOR"
alias v="\$EDITOR"
alias h='history'
alias jl='jobs -l'

# git aliases
alias ga='git add'
alias gp='git push'
alias gpom='git push origin master'
alias gc='git commit -m'
alias gs='git status -sb'
alias gb='git branch'
alias gbl='git-blame-colored'
alias gdd='git diff'
alias gd='cdiff -s'
alias gdt='git difftool'
alias gdl="git diff -w -G'(^[^\*# ])|(^#\w)|(^\s+[^\*#])'"
alias f='find'
alias br='brew'
alias gl='git log --oneline --abbrev-commit --all --graph --decorate --color --no-merges'
alias glm='git log --oneline --abbrev-commit --all --graph --decorate --color'
alias gll="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %C(magenta)(%cn)%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative --left-right"
alias gu='git-up'
alias gr='grunt'
alias listening='lsof +c0 -Pni -sTCP:LISTEN'
# yellow for paths, magenta for matches
alias ag='ag --color-path=33 --color-match=35'
alias srct="tree -d -L 3 -I 'node_modules|bin|server|bower_components'"
alias gf='git flow'
alias gff='git flow feature'
alias dw='~/Applications/DeltaWalker.app/Contents/MacOS/DeltaWalker -pwd=$(pwd)'
alias prettymd='pandoc -t markdown --atx-headers --no-wrap'
alias str='stree'
alias io='ionic'
alias iolive='ionic serve --livereload --consolelogs --serverlogs'
alias ioemu='ionic emulate ios --consolelogs --serverlogs'
alias ioemuipad='ionic emulate ios --consolelogs --serverlogs --target="iPad-Air"'
alias ioemulive='ionic emulate ios --consolelogs --serverlogs'
alias wlb='time wl build --verbose'
alias wld='time wl deploy --verbose'
alias wlbd='wlb && wld'
alias timing='curl -w "@~/castle/curl-timeformat" -o /dev/null -s'
alias va='vagrant'

alias cfl=cf-log

alias less='less -x4 -m -N -g -i -J --underline-special -Q'
alias newletter='cp ~/Dropbox/Projects/panletter/letter.md .'
