#! /bin/bash
# Some example alias instructions
# If these are enabled they will be used instead of any instructions
# they may mask.  For example, alias rm='rm -i' will mask the rm
# application.  To override the alias instruction use a \ before, ie
# \rm will call the real rm not the alias.

# Interactive operation...
# alias rm='rm -i'
# alias cp='cp -i'
# alias mv='mv -i'

# Misc :)
# alias less='less -r'                          # raw control characters
# alias whence='type -a'                        # where, of a sort

# Default to human readable figures
alias df='df -h'
alias du='du -h'

# Some shortcuts for different directory listings
# alias ls='ls -hF --color=tty'                 # classify files in colour
# alias dir='ls --color=auto --format=vertical'
# alias vdir='ls --color=auto --format=long'
alias ll='ls -l'
alias la='ls -A'
alias l='ls -lAF'
#alias lc='ls -CF'
alias lc="(printf 'PERM LINKS OWNER GROUP SIZE MONTH DAY HH:MM/YEAR NAME\n'; ls -la | sed 1d) | column -t"
alias cd..="cd .."
alias ..="cd .."
alias ...="cd ..."
alias md="mkdir"
alias grep='grep --color'
#alias mp="makeProject"
#alias sp=". setProject"
alias pgrep="ps aux| grep"
alias t='task'

# If using Linux alias pbcopy and pbpaste
if [[ "$OSTYPE" =~ ^linux ]]; then
	alias pbcopy='xsel --clipboard --input'
	alias pbpaste='xsel --clipboard --output'
fi

alias e="$EDITOR"
alias h='history'
alias j='jobs -l'

# git aliases
alias ga='git add'
alias gp='git push'
alias gpom='git push origin master'
alias gc='git commit -m'
alias gs='git status -sb'
alias gb='git branch'
alias gd='git diff'
alias f='find'
alias br='brew'
alias gl='git log --oneline --abbrev-commit --all --graph --decorate --color'
