# ~/.bashrc: executed by bash(1) for non-login shells.
# startup debugging
STARTUP="${STARTUP}~/.bashrc, "

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

export TOOLS=~/Tools
include functions
include env
include config
include aliases
