" set guioptions-=m " turn off menu bar
set guioptions-=T " turn off toolbar
set ch=2 " Make command line two lines high
set mousehide " Hide the mouse when typing text

" Make shift-insert work like in Xterm
map <S-Insert> <MiddleMouse>
map! <S-Insert> <MiddleMouse>
set clipboard=unnamed " use os clipboard for vim cut/paste actions
syntax enable

" if has('gui_running')
"   set background=light
"   let g:solarized_termcolors=256
"   colorscheme solarized
" endif

" fix background in mim
highlight Normal guibg=#fdf6e3
