" set guioptions-=m " turn off menu bar
set guioptions-=T " turn off toolbar
if has("mac") || has("macunix")
	set guifont=Monaco\ for\ Powerline:h13
	" set guifont=Fira\ Code:h12 " for Fira Code
	set macligatures
endif
set ch=2 " Make command line two lines high
set mousehide " Hide the mouse when typing text

" Make shift-insert work like in Xterm
map <S-Insert> <MiddleMouse>
map! <S-Insert> <MiddleMouse>
set clipboard=unnamed " use os clipboard for vim cut/paste actions
" syntax enable

" fix background in mvim
highlight Normal guibg=#fdf6e3

" maximize window without going fullscreen
set lines=999
set columns=999

if has('python3')
    command! -nargs=1 Py py3 <args>
    set pythonthreedll=/usr/local/Frameworks/Python.framework/Versions/3.6/Python
    set pythonthreehome=/usr/local/Frameworks/Python.framework/Versions/3.6
else
    command! -nargs=1 Py py <args>
    set pythondll=/usr/local/Frameworks/Python.framework/Versions/2.7/Python
    set pythonhome=/usr/local/Frameworks/Python.framework/Versions/2.7
endif
